export const GENRES_ACTIONS = {
  FETCHING: "GENRES_ACTIONS_FETCHING",
  SUCCESS_FETCH: "GENRES_ACTIONS_SUCCESS_FETCH",
  ERROR_FETCH: "GENRES_ACTIONS_ERROR_FETCH"
};

export const GAMES_ACTIONS = {
  FETCHING: "GAMES_ACTIONS_FETCHING",
  SUCCESS_FETCH: "GAMES_ACTIONS_SUCCESS_FETCH",
  ERROR_FETCH: "GAMES_ACTIONS_ERROR_FETCH"
};
